/home/anders/Documents -> privat/2_HP_pav/Documents
/home/anders/Pictures  -> privat/2_HP_pav/Pictures
/home/anders/Projects  -> privat/2_HP_pav/Projects

/home/anders/Music     -> privat/2_HP_pav/Music
/home/anders/Torrents   -> privat/2_HP_pav/Torrents

EXCLUDE:
/home/anders/Downloads/**
.cache/**
.snap/**
EXCLUDE:
/home/anders/Downloads/**
.cache/**
.snap/**
