# SmartCloud folder sync configuration
# Format:
# LOCAL_PATH -> REMOTE_PATH

# Custom destination folders (processed first)
/home/user/Music     -> myfolder/Music
/home/user/Torrents  -> myfolder/Torrents

# Main system backup
/home/user -> myfolder/devicefolder


# Global exclusions
EXCLUDE:
/home/user/Downloads/**
.cache/**
.snap/**
.local/share/Trash/**

# Development junk
node_modules/**
dist/**
build/**
target/**

# Temporary files
*.tmp
*.part
*.swp



